<img src="http://files.oproject.org/img/HeaderOpenData.png">
# Python Basics
## Printing Hello World

In [2]:
print("Hello kitty world!")

Hello kitty world!


## Using Python as a Calculator

In [10]:
def cube(x):
    return x*x*x

print (cube(6))

216


In [ ]:
2 + 2

In [ ]:
4 / 2

In [ ]:
2**2

## Print a List of Words with a Loop

In [ ]:
words=["hello","cruel","world"]

for word in words:
    print(word)

In [72]:
def sum_two_numbers(a,b):
 return a + b

 if a==0:

     return a - b 

print(sum_two_numbers(2,3))

SyntaxError: 'return' outside function (<ipython-input-72-97ea5d86ece2>, line 6)

In [41]:
from array import *
arrayname = array('i', [1,2,3,4,5,6,7])
for i in arrayname:
    print(i)

1
2
3
4
5
6
7


In [69]:
from numpy import matrix
from numpy import linalg
x = matrix( [[1,1,1], [2,2,2], [3,3,3]])
y = matrix( [[4,4,4], [5,5,5], [6,6,6]])
z = matrix( [[9,9,9], [10,10,10], [11,11,11]])

print x.T
print x*y
print x.I
print linalg.solve(x,y)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[15 15 15]
 [30 30 30]
 [45 45 45]]


LinAlgError: Singular matrix

## Create Your Own Function

In [ ]:
def square(x):
    
    return x*x

## Use Your Function

In [ ]:
print(square(2))

## Import Useful Modules

In [28]:
from math import pi

In [29]:
print(pi)

3.14159265359


## Exercise: Import sine (sin) Function from math Library and use it to compute sin($\pi$/2)

In [62]:
from math import sin 
from math import cos
print(cos(pi))

-1.0


In [36]:
print(sin(pi/2))

1.0


## Same but Using Dot Notation

In [64]:
import math
math.pi

3.141592653589793

In [63]:
math.pi

NameError: name 'math' is not defined

## More About Dot Notation
### Fido is a DOG. 
### He eats, runs and plays.

Fido.eats() <BR> <BR>
Fido.runs() <BR> <BR>
Fido.plays() <BR> <BR>

## Exercise: Please use dot notation with sine (sin) function from the math library to compute sin(pi/2)

In [ ]:
import math

In [65]:
math.sin(pi/2)

1.0